#!/usr/bin/perl -w
use strict;

# given an executable, identify which mpi library is being used

my $prog = "extract_mpi";

# check that the user provided some arguments
if (@ARGV < 1) {
  print "Usage: $prog <args>\n";
  exit 1;
}

# assume that we won't determine the MPI-compiler type
my $mpi = undef;

# run through each argument until we find one that looks like
# it links to an MPI library
foreach my $arg (@ARGV) {
  if (-x $arg) {
    my $ldd = `ldd $arg`;
    if ($? == 0) {
      # got something from ldd,
      # run through the ldd lines and look for one that looks like MPI
      my @lines = split("\n", $ldd);
      foreach my $line (@lines) {
        if ($line =~ /(mvapich-\w+).*libmpich.so/) {
          # seems to link to mvapich
          $mpi = $1;
          last;
        } elsif ($line =~ /(mvapich2-\w+).*libmpich.so/) {
          # seems to link to mvapich2
          $mpi = $1;
          last;
        } elsif ($line =~ /(openmpi-\w+).*libmpi.so/) {
          # seems to link to openmpi
          $mpi = $1;
          last;
        }
      }
    }
  }

  # break out if we found something
  if (defined $mpi) {
    last;
  }
}

# print something if we found it
if (defined $mpi) {
  print "$mpi\n";
  exit 0;
}

# otherwise, exit with error
print "$prog: ERROR: Could not identify MPI library for executable: ", join(" ", @ARGV), "\n";
exit 1;
